"""Install the git hook that rebuilds the code graph after every commit.

    python tools/graphify/install_hook.py                    # install
    python tools/graphify/install_hook.py --vault D:/vault    # install, mirror to a vault
    python tools/graphify/install_hook.py --uninstall

## Why post-commit and not pre-commit

The graph's output is gitignored, so there is nothing for a pre-commit hook to add to the
commit — it would only make you wait before every commit for a file that the commit will
not contain. Running afterwards gives the same freshness at no cost to the commit itself.

The more important reason is failure behaviour. A pre-commit hook that exits non-zero
**aborts the commit**. This tool is a convenience; a bug in it, a missing Python, or a
vault on a disconnected drive must never stand between someone and committing their work.
A post-commit hook's exit status is ignored by git, so the worst case is a stale graph and
a printed warning.

## Why the hook is generated rather than committed

Git does not version `.git/hooks`, by design — a repository cannot silently make your
machine run code on clone. So the hook has to be installed deliberately, once, per clone.
Generating it from this script keeps that one manual step honest and repeatable, and lets
the vault path live in the generated file rather than in the public repository.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

HOOK_NAME = "post-commit"

# The marker is what makes this idempotent: an existing hook carrying it was written by us
# and can be replaced, while one without it is somebody else's and must not be clobbered.
MARKER = "# >>> graphify post-commit hook >>>"

TEMPLATE = """#!/bin/sh
{marker}
# Rebuilds the offline code graph after each commit. Generated by
# tools/graphify/install_hook.py — edit that, not this.
#
# Every line below is deliberately non-fatal. git ignores a post-commit hook's exit status,
# but a hook that prints a Python traceback after every commit is its own kind of failure,
# so errors are summarised instead.
{vault_line}
if command -v python >/dev/null 2>&1; then
    PY=python
elif command -v python3 >/dev/null 2>&1; then
    PY=python3
else
    echo "graphify: no python on PATH, skipping code graph" >&2
    exit 0
fi

"$PY" "$(git rev-parse --show-toplevel)/tools/graphify/graphify.py" >/dev/null 2>&1 \\
    && echo "graphify: code graph updated" \\
    || echo "graphify: code graph update failed (harmless; run it by hand to see why)" >&2

exit 0
"""


class HookInstaller:
    """Writes, replaces or removes the post-commit hook for one repository."""

    def __init__(self, repo_root: Path) -> None:
        self._root = repo_root

    @classmethod
    def discover(cls) -> "HookInstaller":
        """Find the repository root via git rather than assuming this file's location.

        Asking git means the script still works from a worktree or a submodule, where the
        real hooks directory is not `<root>/.git/hooks` at all.
        """
        result = subprocess.run(
            ["git", "rev-parse", "--show-toplevel"],
            capture_output=True, text=True, check=False,
        )
        if result.returncode != 0:
            raise SystemExit("not inside a git repository")
        return cls(Path(result.stdout.strip()))

    def _hooks_dir(self) -> Path:
        """The directory git actually reads hooks from.

        `git rev-parse --git-path hooks` is used instead of `.git/hooks` because the two
        differ whenever `core.hooksPath` is set or the checkout is a linked worktree — in
        which case writing to `.git/hooks` produces a hook that is never run, and the
        symptom is a tool that appears installed and silently does nothing.
        """
        result = subprocess.run(
            ["git", "rev-parse", "--git-path", "hooks"],
            cwd=str(self._root), capture_output=True, text=True, check=False,
        )
        relative = result.stdout.strip() if result.returncode == 0 else ".git/hooks"
        path = Path(relative)
        return path if path.is_absolute() else self._root / relative

    def install(self, vault: str | None) -> Path:
        hooks = self._hooks_dir()
        hooks.mkdir(parents=True, exist_ok=True)
        target = hooks / HOOK_NAME

        if target.exists():
            existing = target.read_text(encoding="utf-8", errors="replace")
            if MARKER not in existing:
                raise SystemExit(
                    f"{target} already exists and was not written by graphify.\n"
                    "Refusing to overwrite it. Merge the two by hand, or remove it first."
                )

        vault_line = (
            f'GRAPHIFY_VAULT="{vault}"\nexport GRAPHIFY_VAULT\n' if vault else
            "# No vault configured. Set GRAPHIFY_VAULT here to mirror the report into an\n"
            "# Obsidian vault as well as into .graphify/.\n"
        )
        target.write_text(
            TEMPLATE.format(marker=MARKER, vault_line=vault_line),
            encoding="utf-8",
            newline="\n",
        )
        # Executable matters on POSIX and is harmless on Windows, where git ships its own
        # shell and runs the hook regardless of the mode bit.
        target.chmod(0o755)
        return target

    def uninstall(self) -> bool:
        target = self._hooks_dir() / HOOK_NAME
        if not target.exists():
            return False
        if MARKER not in target.read_text(encoding="utf-8", errors="replace"):
            raise SystemExit(f"{target} was not written by graphify; leaving it alone.")
        target.unlink()
        return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument(
        "--vault",
        help="Path to an Obsidian vault. The report is mirrored to "
             "<vault>/03-Build/graphs/<project>/graph.md as well as to .graphify/.",
    )
    parser.add_argument("--uninstall", action="store_true", help="Remove the hook.")
    args = parser.parse_args()

    installer = HookInstaller.discover()

    if args.uninstall:
        print("graphify: hook removed" if installer.uninstall()
              else "graphify: no hook installed")
        return 0

    if args.vault and not Path(args.vault).expanduser().is_dir():
        # Refused rather than accepted quietly: a typo'd vault path would install a hook
        # that silently never mirrors anything, and the whole point of the flag is the
        # mirroring.
        raise SystemExit(f"vault path is not a directory: {args.vault}")

    target = installer.install(args.vault)
    print(f"graphify: installed {target}")
    print("graphify: the graph will rebuild after every commit; .graphify/ is gitignored")
    if args.vault:
        print(f"graphify: mirroring to {args.vault}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
